### ISSUE TITLE
Implement livenessProbe and readinessProbe for Openshift deployment

### ISSUE THREAD

**Issue by maoo** [symphonyoss/bot-unfurl#6]
The main goal is to provide an endpoint from the bot to validate the liveliness and readiness of the service.

Check Openshift docs to understand how to define probes - https://docs.openshift.com/enterprise/3.1/dev_guide/application_health.html

Current definitions of (Openshift) Build and Deployment are reported here for reference - https://gist.github.com/maoo/60d86510735b81faa1bce8b1f959fe21

The EchoBot has a simple implementation that serves /status endpoint on port 4567, see implementation on https://github.com/symphonyoss/symphony-java-sample-bots/blob/experimental/src/main/java/org/symphonyoss/simplebot/EchoBot.java#L88-L102

the `readinessProbe` is defined below:
```
          readinessProbe:
            httpGet:
              path: /status
              port: 4567
            initialDelaySeconds: 15
            timeoutSeconds: 1
```
